#!/usr/bin/env tsx
/**
 * OmniRule CRUD Generator
 *
 * Reads prisma/schema.prisma → generates full CRUD stack for a model.
 * Output: route handlers, service, Zod schema, TypeScript types, test scaffold.
 *
 * Usage:
 *   npm run tool:crud -- User
 *   npm run tool:crud -- User --dry-run
 *   npm run tool:crud -- User --out src/features/users
 *   npm run tool:crud -- --list    (show available models)
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = process.cwd();

// ─── Prisma schema parser ─────────────────────────────────────────────────────

interface PrismaField {
  name: string;
  type: string;
  isOptional: boolean;
  isArray: boolean;
  isId: boolean;
  isRelation: boolean;
  hasDefault: boolean;
  isCreatedAt: boolean;
  isUpdatedAt: boolean;
}

interface PrismaModel {
  name: string;
  fields: PrismaField[];
}

function findSchema(): string | null {
  const candidates = [
    path.join(ROOT, 'prisma', 'schema.prisma'),
    path.join(ROOT, 'schema.prisma'),
  ];
  return candidates.find(p => fs.existsSync(p)) ?? null;
}

function parseSchema(schemaPath: string): PrismaModel[] {
  const content = fs.readFileSync(schemaPath, 'utf-8');
  const models: PrismaModel[] = [];

  const modelRe = /model\s+(\w+)\s*\{([^}]+)\}/g;
  let modelMatch: RegExpExecArray | null;

  while ((modelMatch = modelRe.exec(content)) !== null) {
    const modelName = modelMatch[1];
    const body = modelMatch[2];
    const fields: PrismaField[] = [];

    for (const line of body.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('@@')) continue;

      const fieldRe = /^(\w+)\s+(\w+)(\[\])?\s*(\?)?(.*)$/;
      const fm = fieldRe.exec(trimmed);
      if (!fm) continue;

      const [, name, type, arrayMark, optMark, rest] = fm;
      const isRelation = /^[A-Z]/.test(type) && type !== 'String' && type !== 'Int' &&
        type !== 'Float' && type !== 'Boolean' && type !== 'DateTime' &&
        type !== 'Json' && type !== 'Decimal' && type !== 'BigInt' && type !== 'Bytes';

      fields.push({
        name,
        type,
        isOptional: !!optMark || rest.includes('@default') || rest.includes('?'),
        isArray: !!arrayMark,
        isId: rest.includes('@id'),
        isRelation,
        hasDefault: rest.includes('@default'),
        isCreatedAt: rest.includes('@default(now())') && name.toLowerCase().includes('created'),
        isUpdatedAt: rest.includes('@updatedAt'),
      });
    }

    if (fields.length > 0) models.push({ name: modelName, fields });
  }

  return models;
}

// ─── Type mapping ─────────────────────────────────────────────────────────────

function prismaToTs(type: string): string {
  const map: Record<string, string> = {
    String: 'string', Int: 'number', Float: 'number', Boolean: 'boolean',
    DateTime: 'Date', Json: 'Record<string, unknown>', Decimal: 'number',
    BigInt: 'bigint', Bytes: 'Buffer',
  };
  return map[type] ?? type;
}

function prismaToZod(type: string): string {
  const map: Record<string, string> = {
    String: 'z.string()', Int: 'z.number().int()', Float: 'z.number()',
    Boolean: 'z.boolean()', DateTime: 'z.string().datetime()',
    Json: 'z.record(z.unknown())', Decimal: 'z.number()', BigInt: 'z.bigint()',
  };
  return map[type] ?? `z.string()`;
}

// ─── Template generators ──────────────────────────────────────────────────────

function plural(name: string): string {
  if (name.endsWith('y')) return name.slice(0, -1) + 'ies';
  if (name.endsWith('s')) return name + 'es';
  return name + 's';
}

function camel(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function generateTypes(model: PrismaModel): string {
  const fields = model.fields.filter(f => !f.isRelation);
  const idField = fields.find(f => f.isId);
  const tsFields = fields.map(f => {
    const tsType = prismaToTs(f.type) + (f.isArray ? '[]' : '');
    return `  ${f.name}${f.isOptional ? '?' : ''}: ${tsType};`;
  });

  const createFields = fields
    .filter(f => !f.isId && !f.isCreatedAt && !f.isUpdatedAt && !f.hasDefault)
    .map(f => `  ${f.name}${f.isOptional ? '?' : ''}: ${prismaToTs(f.type) + (f.isArray ? '[]' : '')};`);

  const updateFields = fields
    .filter(f => !f.isId && !f.isCreatedAt && !f.isUpdatedAt)
    .map(f => `  ${f.name}?: ${prismaToTs(f.type) + (f.isArray ? '[]' : '')};`);

  return `// Auto-generated by OmniRule crud-gen — ${new Date().toISOString().split('T')[0]}

export interface ${model.name} {
${tsFields.join('\n')}
}

export interface Create${model.name}Input {
${createFields.join('\n')}
}

export interface Update${model.name}Input {
${updateFields.join('\n')}
}

export interface ${model.name}ListResponse {
  data: ${model.name}[];
  total: number;
  page: number;
  pageSize: number;
}
`;
}

function generateSchema(model: PrismaModel): string {
  const fields = model.fields.filter(f => !f.isRelation);
  const createFields = fields
    .filter(f => !f.isId && !f.isCreatedAt && !f.isUpdatedAt && !f.hasDefault)
    .map(f => {
      let zodExpr = prismaToZod(f.type);
      if (f.isArray) zodExpr = `z.array(${zodExpr})`;
      if (f.isOptional) zodExpr += '.optional()';
      return `  ${f.name}: ${zodExpr},`;
    });

  const updateFields = fields
    .filter(f => !f.isId && !f.isCreatedAt && !f.isUpdatedAt)
    .map(f => {
      let zodExpr = prismaToZod(f.type);
      if (f.isArray) zodExpr = `z.array(${zodExpr})`;
      return `  ${f.name}: ${zodExpr}.optional(),`;
    });

  return `import { z } from 'zod';

export const Create${model.name}Schema = z.object({
${createFields.join('\n')}
});

export const Update${model.name}Schema = z.object({
${updateFields.join('\n')}
});

export const ${model.name}IdSchema = z.object({
  id: z.string(),
});

export type Create${model.name}Input = z.infer<typeof Create${model.name}Schema>;
export type Update${model.name}Input = z.infer<typeof Update${model.name}Schema>;
`;
}

function generateService(model: PrismaModel): string {
  const m = camel(model.name);
  const idField = model.fields.find(f => f.isId);
  const idType = idField ? prismaToTs(idField.type) : 'string';

  return `import { prisma } from '@/lib/prisma';
import type { Create${model.name}Input, Update${model.name}Input } from '@/types/${m}';

export async function get${model.name}s(page = 1, pageSize = 20) {
  const skip = (page - 1) * pageSize;
  const [data, total] = await Promise.all([
    prisma.${m}.findMany({ skip, take: pageSize, orderBy: { createdAt: 'desc' } }),
    prisma.${m}.count(),
  ]);
  return { data, total, page, pageSize };
}

export async function get${model.name}ById(id: ${idType}) {
  return prisma.${m}.findUnique({ where: { id } });
}

export async function create${model.name}(input: Create${model.name}Input) {
  return prisma.${m}.create({ data: input });
}

export async function update${model.name}(id: ${idType}, input: Update${model.name}Input) {
  return prisma.${m}.update({ where: { id }, data: input });
}

export async function delete${model.name}(id: ${idType}) {
  return prisma.${m}.delete({ where: { id } });
}
`;
}

function generateListRoute(model: PrismaModel): string {
  const m = camel(model.name);
  const pl = plural(m);

  return `import { NextRequest, NextResponse } from 'next/server';
import { get${model.name}s, create${model.name} } from '@/lib/services/${m}.service';
import { Create${model.name}Schema } from '@/lib/schemas/${m}.schema';
import { ZodError } from 'zod';

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = request.nextUrl;
    const page = parseInt(searchParams.get('page') ?? '1');
    const pageSize = Math.min(parseInt(searchParams.get('pageSize') ?? '20'), 100);

    const result = await get${model.name}s(page, pageSize);
    return NextResponse.json(result);
  } catch (error) {
    console.error('[GET /${pl}]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const input = Create${model.name}Schema.parse(body);
    const item = await create${model.name}(input);
    return NextResponse.json(item, { status: 201 });
  } catch (error) {
    if (error instanceof ZodError) {
      return NextResponse.json({ error: 'Validation failed', details: error.errors }, { status: 422 });
    }
    console.error('[POST /${pl}]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
`;
}

function generateDetailRoute(model: PrismaModel): string {
  const m = camel(model.name);
  const pl = plural(m);

  return `import { NextRequest, NextResponse } from 'next/server';
import { get${model.name}ById, update${model.name}, delete${model.name} } from '@/lib/services/${m}.service';
import { Update${model.name}Schema } from '@/lib/schemas/${m}.schema';
import { ZodError } from 'zod';

interface Params { params: { id: string } }

export async function GET(_req: NextRequest, { params }: Params) {
  try {
    const item = await get${model.name}ById(params.id);
    if (!item) return NextResponse.json({ error: '${model.name} not found' }, { status: 404 });
    return NextResponse.json(item);
  } catch (error) {
    console.error('[GET /${pl}/:id]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PATCH(request: NextRequest, { params }: Params) {
  try {
    const body = await request.json();
    const input = Update${model.name}Schema.parse(body);
    const item = await update${model.name}(params.id, input);
    return NextResponse.json(item);
  } catch (error) {
    if (error instanceof ZodError) {
      return NextResponse.json({ error: 'Validation failed', details: error.errors }, { status: 422 });
    }
    console.error('[PATCH /${pl}/:id]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(_req: NextRequest, { params }: Params) {
  try {
    await delete${model.name}(params.id);
    return new NextResponse(null, { status: 204 });
  } catch (error) {
    console.error('[DELETE /${pl}/:id]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
`;
}

function generateTest(model: PrismaModel): string {
  const m = camel(model.name);
  const idField = model.fields.find(f => f.isId);

  const createFields = model.fields
    .filter(f => !f.isRelation && !f.isId && !f.isCreatedAt && !f.isUpdatedAt && !f.hasDefault)
    .map(f => {
      const val = f.type === 'String' ? `'test-${f.name}'` :
                  f.type === 'Int' || f.type === 'Float' ? '1' :
                  f.type === 'Boolean' ? 'true' : `'test'`;
      return `    ${f.name}: ${val},`;
    });

  return `import { describe, it, expect, beforeEach, vi } from 'vitest';
import {
  get${model.name}s,
  get${model.name}ById,
  create${model.name},
  update${model.name},
  delete${model.name},
} from '@/lib/services/${m}.service';

vi.mock('@/lib/prisma', () => ({
  prisma: {
    ${m}: {
      findMany: vi.fn(),
      findUnique: vi.fn(),
      count: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
    },
  },
}));

import { prisma } from '@/lib/prisma';

describe('${model.name} Service', () => {
  const mock${model.name} = {
    id: 'test-id-1',
${createFields.join('\n')}
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  beforeEach(() => vi.clearAllMocks());

  describe('get${model.name}s', () => {
    it('returns paginated list', async () => {
      (prisma.${m}.findMany as any).mockResolvedValue([mock${model.name}]);
      (prisma.${m}.count as any).mockResolvedValue(1);

      const result = await get${model.name}s(1, 20);

      expect(result.data).toHaveLength(1);
      expect(result.total).toBe(1);
      expect(result.page).toBe(1);
    });
  });

  describe('get${model.name}ById', () => {
    it('returns item when found', async () => {
      (prisma.${m}.findUnique as any).mockResolvedValue(mock${model.name});
      const result = await get${model.name}ById('test-id-1');
      expect(result).toEqual(mock${model.name});
    });

    it('returns null when not found', async () => {
      (prisma.${m}.findUnique as any).mockResolvedValue(null);
      const result = await get${model.name}ById('nonexistent');
      expect(result).toBeNull();
    });
  });

  describe('create${model.name}', () => {
    it('creates and returns item', async () => {
      (prisma.${m}.create as any).mockResolvedValue(mock${model.name});
      const input = {
${createFields.join('\n')}
      };
      const result = await create${model.name}(input as any);
      expect(result).toEqual(mock${model.name});
      expect(prisma.${m}.create).toHaveBeenCalledWith({ data: input });
    });
  });

  describe('update${model.name}', () => {
    it('updates and returns item', async () => {
      const updated = { ...mock${model.name} };
      (prisma.${m}.update as any).mockResolvedValue(updated);
      const result = await update${model.name}('test-id-1', {});
      expect(result).toEqual(updated);
    });
  });

  describe('delete${model.name}', () => {
    it('deletes item', async () => {
      (prisma.${m}.delete as any).mockResolvedValue(mock${model.name});
      await delete${model.name}('test-id-1');
      expect(prisma.${m}.delete).toHaveBeenCalledWith({ where: { id: 'test-id-1' } });
    });
  });
});
`;
}

// ─── File writer ──────────────────────────────────────────────────────────────

interface GeneratedFile { path: string; content: string; }

function buildFiles(model: PrismaModel, outBase?: string): GeneratedFile[] {
  const m = camel(model.name);
  const pl = plural(m);
  const base = outBase ?? ROOT;

  return [
    { path: path.join(base, 'types', `${m}.ts`),                          content: generateTypes(model) },
    { path: path.join(base, 'lib', 'schemas', `${m}.schema.ts`),          content: generateSchema(model) },
    { path: path.join(base, 'lib', 'services', `${m}.service.ts`),        content: generateService(model) },
    { path: path.join(base, 'app', 'api', pl, 'route.ts'),                content: generateListRoute(model) },
    { path: path.join(base, 'app', 'api', pl, '[id]', 'route.ts'),        content: generateDetailRoute(model) },
    { path: path.join(base, '__tests__', `${m}.service.test.ts`),         content: generateTest(model) },
  ];
}

// ─── CLI ──────────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const modelArg = args.find(a => !a.startsWith('--'));
const dryRun = args.includes('--dry-run');
const listMode = args.includes('--list');
const outArg = args.find(a => a.startsWith('--out='))?.split('=')[1];

const schemaPath = findSchema();

if (listMode) {
  if (!schemaPath) { console.error('[CrudGen] No prisma/schema.prisma found'); process.exit(1); }
  const models = parseSchema(schemaPath);
  console.log('\n[CrudGen] Available models:');
  models.forEach(m => console.log(`  ${m.name} (${m.fields.length} fields)`));
  process.exit(0);
}

if (!modelArg) {
  console.error('Usage: npm run tool:crud -- ModelName [--dry-run] [--out=src/features/name] [--list]');
  process.exit(1);
}

if (!schemaPath) {
  console.log('[CrudGen] No prisma/schema.prisma found — generating with minimal scaffold');
}

const models = schemaPath ? parseSchema(schemaPath) : [];
const model = models.find(m => m.name.toLowerCase() === modelArg.toLowerCase());

if (!model && schemaPath && models.length > 0) {
  console.error(`[CrudGen] Model "${modelArg}" not found in schema.`);
  console.error(`Available: ${models.map(m => m.name).join(', ')}`);
  process.exit(1);
}

const targetModel: PrismaModel = model ?? {
  name: modelArg.charAt(0).toUpperCase() + modelArg.slice(1),
  fields: [
    { name: 'id', type: 'String', isOptional: false, isArray: false, isId: true, isRelation: false, hasDefault: true, isCreatedAt: false, isUpdatedAt: false },
    { name: 'name', type: 'String', isOptional: false, isArray: false, isId: false, isRelation: false, hasDefault: false, isCreatedAt: false, isUpdatedAt: false },
    { name: 'createdAt', type: 'DateTime', isOptional: false, isArray: false, isId: false, isRelation: false, hasDefault: true, isCreatedAt: true, isUpdatedAt: false },
    { name: 'updatedAt', type: 'DateTime', isOptional: false, isArray: false, isId: false, isRelation: false, hasDefault: true, isCreatedAt: false, isUpdatedAt: true },
  ],
};

const files = buildFiles(targetModel, outArg ? path.resolve(ROOT, outArg) : undefined);

console.log(`\n[CrudGen] Generating CRUD for: ${targetModel.name}`);
if (dryRun) console.log('  (dry run — no files written)\n');

for (const f of files) {
  const relPath = path.relative(ROOT, f.path);
  if (dryRun) {
    console.log(`  📄 ${relPath}`);
  } else {
    fs.mkdirSync(path.dirname(f.path), { recursive: true });
    if (fs.existsSync(f.path)) {
      console.log(`  ⚠️  SKIP (exists): ${relPath}`);
    } else {
      fs.writeFileSync(f.path, f.content, 'utf-8');
      console.log(`  ✓ ${relPath}`);
    }
  }
}

console.log(`\n[CrudGen] Done — ${files.length} files ${dryRun ? 'previewed' : 'generated'}`);
if (!dryRun) {
  console.log(`  Next: implement auth checks in route handlers`);
  console.log(`  Next: customize service queries as needed`);
}
